name: 新アイテムのリクエスト
description: 気軽にリクエストしてください。画像は作成後のIssueに添付してください。
title: '[リクエスト]: '
labels: ['feature']
body:
  - type: input
    id: title
    attributes:
      label: タイトル
    validations:
      required: true
  - type: input
    id: href
    attributes:
      label: URL
    validations:
      required: true
  - type: dropdown
    id: tag
    validations:
      required: true
    attributes:
      label: タグ
      multiple: true
      options:
        - no-license-required
        - available-for-commercial-use
        - photo
        - avatar
        - illust
        - css
        - icon
        - free
        - video
        - public-domain
        - font
        - icon-font
        - audio
        - logo
        - .pdf
        - .svg
        - .png
        - .ai
        - .eps
        - mit-license
        - cc-by-nd-4.0
        - cc-by-sa-4.0
