name: 新アイテムのリクエスト
description: お気軽に追加してください。画像はIssueに添付してください。
title: '[リクエスト]: '
labels: ['feature']
projects: []
body:
  - type: input
    id: title
    attributes:
      label: タイトル
    validations:
      required: true
  - type: input
    id: href
    attributes:
      label: URL
    validations:
      required: true
  - type: dropdown
    id: tag
    validations:
      required: true
    attributes:
      label: タグ
      multiple: true
      options:
        - no-license-required
        - photo
        - illust
        - icon
        - free
        - video
        - public-domain
